[ { description: 'Many festivals are celebrated at Arunachaleswarar temple in Tiruvannamalai throughout the year. Among them Karthigai Deepam is the most significant festival that is celebrated with pomp and gaiety at Arunachaleswarar temple.\n\nIn this year Karthikai Deepam falls on (Date) 10th December,2019 .This Karthigai Deepam is celebrated as a ten day festival and it widely known as Karthigai Brahmotsavam.\n\nTiruvannamalai Karthigai Deepam Festival 2019 – 10 Days\n\nThe first day (1.12.2019) – Karthika Deepam festival begins with the hosting of the flag signifying the commencement of the festival also known as Dwajaroghanam. In the morning and night Lord Arunachaleswarar will be taken out on the silver vahana for procession. The Panchamurthis(Panchamurthigal) are also taken out in the procession. The Panchamurthigal are Lord Ganapathi, Lord Murugan, Lord Sandeswarar, Lord Arunachaleswarar and Goddess Parvathi.These processions are carried out on different vahanas after the Deeparadhana is done at the kalyana mandapam.\n\nThe second day (2.12.2019) – Karthigai Deepam festival commences with the Lord Panchamurthigal coming on Indira Vimanam the chariot of Lord Indira.\n\nThe third day (3.12.2019) – Karthigai Deepam festival the ceremony begins at night with the Lord Panchamurthigal coming in procession majestically on the Simha vahana, the chariot of lion. \n\nOn the fourth day (4.12.2019) of Karthikai Deepam the Lord Panchamurthigal comes in the procession that starts at night on the kamadhenu vahanam. The auspicious tree Karpaviruksha is also on the side of the lord. This tree is believed to grant all the wishes that the devotees seek without fail. \n\nThe fifth day (5.12.2019) – Karthikai Deepam festival begins at night. This procession on the silver rishaba vahanam is very appealing and splendid to witness. Lord Panchamurthigal goes on this vahana that is about 25 feet tall. A big umbrella with about 17 feet in diameter is carried along in the procession.\n\nThe sixth day (6.12.2019) – Karthigai Deepam festival commences with a night procession of Lord Panchamurthigal on the silver chariot that is beautifully crafted and simply imposing when it comes around the temple.\n\nThe seventh day (7.12.2019) of Karthikai Deepam festival Lord Panchamurthigal starts with the procession on the Maha ratham that is very huge and it almost occupies the full width of the road. This ratham is made of pure wood that is strong and rugged. T\n\nThe eight day (8.12.2019) – Karthigai Deepam festival begins at night with the Lord Panchamurthigal going out on procession on the huge horse vahana. The speciality of this horse is that all the four legs of this horse are in the air and they do not touch the ground.\n\nThe seventh day (7.12.2019) of Karthikai Deepam festival Lord Panchamurthigal starts with the procession on the Maha ratham that is very huge and it almost occupies the full width of the road. This ratham is made of pure wood that is strong and rugged. T\n\nhe eight day (8.12.2019) – Karthigai Deepam festival begins at night with the Lord Panchamurthigal going out on procession on the huge horse vahana. The speciality of this horse is that all the four legs of this horse are in the air and they do not touch the ground.\n\nOn the ninth day (9.12.2019) of Karthigai Deepam festival the devotees can witness Lord Panchamurthigal going out procession on the Kailasa Vahanam. This ceremony is mostly conducted on the ninth night.\n\nThe tenth day (10.12.2019) – Karthigai Deepam festival starts at around four o clock in the early hours and the Bharani Deepam is lit at the temple. In the evening the Mahadeepam is lit on the top of the hill at around six o clock. This is a very important ceremony during the Karthigai Deepam festival at Tiruvannamalai. Arunachaleswarar is said to be visually represented in the form of agni on the hill top. There is a very mammoth gathering on this day at the Arunachaleswarar temple to witness this glorious and sacred event. The night ceremony starts with Lord Periya nayagar going out procession on the Rishaba vahanam that is made of gold. This is another spectacular event at Arunachaleswar temple at Tiruvannamalai.\n\n#Thiruvannamalai #KarthigaiDeepamFestival #Girivalamwalk #Parikramawalk #Spiritualtravel #Spiritualwalk #Spiritualtripping #SouthIndiaTourism #Travelandtourism #IncredibleIndia #travelbug #wanderlust #mountains #adventure #tourist #wonderfulplaces #worldcaptures #beautifullandscape #travelwithtnt #wanderers #HappyTraveller #TheNextTripSee more See less',
    date: 'DEC 9',
    title: 'Thiruvannamalai Karthigai Deepam Festival 2019',
    place: '9 Dec–11 Dec · The Next Trip · Bangalore, India' },
  { description: 'Sandalwood Beauty Queen Hariprriya Birthday CelebrationSee more See less',
    date: 'OCT 29',
    title: 'Haripriya Birthday',
    place: 'Tue 10:00 UTC+05:30 · Bangalore, India · Bangalore, India' },
  { description: 'Festival season is about to kick off, and Designer Studio is here to get you ready on time! \n\nWith our most hyped, most colorful, most exciting event of the year, \'THE FESTIVAL EDITION\' is set to be the best in-store shopping event we\'ve hosted yet! \n \nWe will be showing you some of the very best Independent Festival Fashion Designers around. From women\'s +kids+Men\'s festival wear to accessories, home decor, jewelry, to wellness products and much more!\nDate : 1st & 2nd October from 10am-8.30pm. \nVenue : Shubh Sankalp Banquet Hall, #539, 9th cross, Kanakapura Rd, Jayanagar, Bangalore.\nContact : 99805 84455/  82172 59778/  98450 48269\nFree Entry. \n\n#designerstudio #designerstudioevents #bangalore #banagloreevents #festival #shoppiingseason #fashionclothing #jewelry #homedecor #diwaliSee more See less',
    date: 'OCT 1',
    title: 'Designer Studio',
    place: '1 Oct–2 Oct · Shubh Sankalp · Bangalore, India' },
  { description: 'Christmas. The time of the year you spend having week long fun with friends and family. Take the celebrations to the next level this year, with Sampoorn\'s "SOUL FLEA - Christmas Edition 2019"\n\nWith over 100+ stalls exhibiting the finest of their products ranging from home décor to jewellery to handicrafts to gardening accessories and eco-friendly organic products. Food stalls will serve you an array of cuisines while lively band performances  from upcoming bands will make your moment. Along with this, there will be live workshops on pottery, clay modelling and several other interesting crafts for children. \n\nCome spend a sunday full of FOOD, FUN and FROLIC at SOUL FLEA Christmas Edition 2019\n\nOn 1 Dec, Sunday ,2019\n\nVenue - Jayamahal Palace, Bangalore\nContact :\nShalini Sudarshan 9845597553,\nKailash Sudarshan 9480337734\nPrema : 9742204002See more See less',
    date: 'DEC 1',
    title: 'SOUL FLEA By Sampoorn- Christmas Edition 2019',
    place: 'Sun 11:00 UTC+05:30 · Jayamahal Palace · Bangalore, India' },
  { description: 'A Word Of Advice : Given the fact that Tadiandamol is a relatively unfamiliar trekking trial, it is highly advisable not to undertake the trek during the off season, unless the participants are being accompanied by a professional guide having ample experience on the trail. It is also a good idea to opt for the rappelling session only if the participants feel comfortable about doing it and not just to fulfill a challenge or to show off their fearlessness in front of other participants.See more See less',
    date: 'NOV 1',
    title: 'Tadiandamol',
    place: '1 Nov–3 Nov · Bangalore, India · Bangalore, India' },
  { description: 'Join us for Dasara celebrations at National College Grounds, Basavanagudi, Bengaluru on Tuesday, October 8, 2019. The festivities include Sri Rama Taraka Yajna, devotional concert, inspirational talk, Ratha procession, Ravana-Kumbhakarna dahana and food festival.\n#Dasara #DasaraBengaluru #ISKCONDasara #DasaraFestivalSee more See less',
    date: 'OCT 8',
    title: 'Dasara Celebration',
    place: 'Tue 14:00 UTC+05:30 · National College Grounds · Bangalore, India' },
  { description: 'South Bangalore Cultural Association in collaboration with Cocept IMC brings to you 23rd Edition of the Durga Pooja at the 2000 year old Cave Temple premises from 4th Oct - 8th October, 2019. Come witness the festivities, enjoy the food and wide array of shopping from local artisans.See more See less',
    date: 'OCT 4',
    title: 'Durga Pooja & Dussehra Mela',
    place: '4 Oct–8 Oct' },
  { description: 'Bengaluru is the house of global cuisine, We love to eat Masala Dose to Enchiladas anything and everything that one can offer. Bengalureans are spoilt by choices when it comes what to eat? The cosmopolitan culture of Bengaluru changed the way we look at food, old school eateries still being favorite for us but we do have the finest restaurants serving Indian global cuisine. This sums up our food love and the exploration we do.\n\nAaharotsava - the festivity of food. An event curated by hardcore foodies who have experienced all cuisines since decades came together to celebrate the food like never before. It is our laborious effort in getting the best of best dishes under one roof, Because "First we eat, then we do everything else"\n\n Bengaluru Aaharotsava is Asia\'s Largest Veg Food Festival.See more See less',
    date: 'OCT 18',
    title: 'Bengaluru Aaharotsava 2019',
    place: 'Fri 10:00 UTC+05:30 · Freedom Park · Bangalore, India' },
  { description: 'Navaratri is here again. It is a tradition at J.V.Vidyapeetha to arrange dolls in school during Navaratri. Excitement spreads and curiosity increases among the children and parents to see new dolls arrangeed in new ways. The Dasara Bombe Habba at JVVP is popular in the neighbourhood as well.\nNavaratri celebrations at JVVP is very unique and special. Its relaxing and enjoyable for children in the midst of mid-term exams. Everybody will look forward to new arrangements and also the snack(bombe bagina) that they get everyday during the festivities. \nThe doll display includes  complete Ramayana, episodes from the Mahabharatha, Bhagavatha, Mysore Dasara Procession and other social celebrations, Indian culture, rural and wild life and so on. \n  ***********ALL ARE WELCOME. ENTRY FREE ***************\nADDRESS: 6th cross, 11th main, R.K.Layout, Padmanabhanagar, Bangalore-560070 (landmark-near Maharaja Agrasena Hospital).\nPh:080-26391509\nDates: 29th Sept to 4th Oct\nTime: 10 am to 4pm.See more See less',
    date: 'OCT 1',
    title: 'Dasara DOLL Exhibition',
    place: 'Tue 10:00 UTC+05:30 · J.V.Vidyapeeth · Bangalore, India' },
  { description: 'Bangalore’s very own celebration of reading and writing. India’s largest independent and community-funded literature fest. 📚| Nov 9-10, 2019See more See less',
    date: 'NOV 9',
    title: 'Bangalore Literature Festival',
    place: '9 Nov–10 Nov · The Lalit Ashok Bangalore · Bangalore, India' },
  { description: '"Bangalore Utsav - Deepavali Shopping Carnival" Organised by Grand Flea Market.\n\nGrand Flea Market proudly invites each and everyone to "Bangalore Utsav - Deepavali Shopping Carnival".\n\nGet ready to shop with wide ranges of Arts & Crafts, Clothing, Jewelry, Home Decor, Furniture, Handicrafts products along with Food, Music, Artisan Performance and much more from all exhibitor across India. \n\nDate: 11th Oct - 20th Oct 2019 (10 Days).\nBetween : 11:00 AM to 7:00 PM\nVenue: Karnataka Chitrakala Parishath, Kumar Krupa Road, Bengaluru.\n\nShopping | Live Performance | Much More...\n\nYES....!\nFREE ENTRY...!\n\nFor event details and stall bookings Contact: 8861792505 / 9036658774.\n\n #Bengaluruutsava #events #bangaloreutsava #exhibitions #bangalore_days #shoppingcarnival #grandfleamarket #handicraft #homedecor #arts #crafts #eventsinbangalore #bangaloreexhibitions #karnatakachitrakalaparishath #ckp  #bangalore_insta #festivalshopping #shopping #freeenetry  #bangalorebloggers #ethnicproducts #ethnicity #colorful #blogger #bloggerstyle #bangalore #bengaluru #nammabengaluru #music #livemusic #kids #family #shopping #familyouting #handloomsarees #traditionaldresses #jewellery #lampshades #furnitures #bedlinen  #woodentoys #bangaloreutsav #entryfree #mustvisit #bangaloreanSee more See less',
    date: 'OCT 11',
    title: 'Bangalore Utsav - Deepavali Shopping Carnival',
    place: 'Fri 11:00 UTC+05:30 · Karnataka Chitrakala Parishath · Bangalore, India' },
  { description: '7th Edition Thump! Celebration Bengaluru Marathon 2019\nEvent Date, Time & Venue : \n\n• Date: Sunday 24th November, 2019.\n\n• Venue: Nice Toll Plaza, Adjacent to PES IT College, Nayandahalli Junction, Ring Road, Near Mysore Road\n\nStart Time: (subject to change)\n\n• Full Marathon – 4.45 am\n\n• 30K Run – 5.30 am\n\n• Half Marathon- 6.00 am\n\n• 10 Kms Run – 6.45 am\n\n• 6 Kms Run – 8.00 am\n\nKindly plan to arrive at the venue at least 30 minutes prior to the race start time\nEvent Categories :\n\n1. 6 Kms Run for participants above 10 yrs (Men & Women) – Non Competitive Category\n\n2. 10 Kms Run : Open Category (16 yrs – 45 yrs), Senior Category (46 yrs – 60 yrs) and Veteran Category (61yrs – Above) (Men & Women) – Competitive category\n\n3. Half Marathon : Open Category (16 yrs – 45 yrs), Senior Category (46 yrs – 60 yrs) and Veteran Category (61 yrs – Above) (Men & Women) – Competitive category\n\n4. 30K Run: Open for participants 18 yrs & above\n\n5. Full Marathon : Open for participants 18 yrs & above\n\nNOTE : ‘ Full Marathon Participants should have Mandatorily run a Timed Half Marathon in 2018 ‘ , Participants opting for Full Marathon needs to mail us the Half Marathon Timed Certificate to contact@lifeiscalling-sports.com post registration for verification . Registration for FM will be accepted based on verification\n\nRegistration Fee : \nEarly Bird Registration Fee till 15th June, 2019:\n\n1. Full Marathon : Rs. 1400\n\n2. 30K Run: Rs.1150\n\n3. Half Marathon: Rs.1000\n\n4. 10 Kms Run: Rs.750\n\n5. 6 Kms Run / Walk : Rs.400\n\nEarly Bird Registration Fee till 15th July, 2019:\n\n1. Full Marathon : Rs. 1450\n\n2. 30K Run: Rs.1200\n\n3. Half Marathon: Rs.1050\n\n4. 10 Kms Run: Rs.800\n\n5. 6 Kms Run / Walk : Rs.450\n\nEarly Bird Registration Fee till 15th August, 2019:\n\n1. Full Marathon : Rs. 1500\n\n2. 30K Run: Rs.1250\n\n3. Half Marathon: Rs.1100\n\n4. 10 Kms Run: Rs.850\n\n5. 6 Kms Run / Walk : Rs.500\n\nEarly Bird Registration Fee till 15th September, 2019:\n\n1. Full Marathon : Rs. 1550\n\n2. 30K Run: Rs.1300\n\n3. Half Marathon: Rs.1150\n\n4. 10 Kms Run: Rs.900\n\n5. 6 Kms Run / Walk : Rs.550\n\n \n\n(Registration fee is inclusive of GST at applicable rate)\n\nRegistration Fee includes Event T-Shirt, Timed Bib, Finisher Medal & Breakfast for participants in Full Marathon, 30K, Half Marathon & 10K Run categories.\n\nFor 6 Kms Run / Walk participants the fee includes Event T-Shirt, Finisher Medal and Breakfast.\n\nLast Date of Registration: 10th November, 2019 (for personalized bibs in FM, 30K, Half Marathon & 10K)\n\nLast date of Online Registration: 16th November, 2019.\n\nPrizes for Winners:\nAll winners in Full Marathon,30K, Half Marathon and 10K Run will receive trophies under Open Category, Senior Category & Veteran Category (Men & Women).\n\nKindly Note: The winners will be decided based on Gun Time and Timing Certificates will be on Chip Time.\nMore Details : \nThe event will attract runners in the Full Marathon, 30K Run, Half Marathon and 10K Run categories from all the major Indian cities.\n\nThe whole idea of the event is celebration, that’s our focus and theme – to celebrate. Hence to add to the celebrative mood will be music bands, traditional dance groups that will perform at the Start / Finish Venue of the event and also performances will happen along the running route.\n\nThe Marathon event is focused mainly to bring about a happy and healthy lifestyle, to induce positive outlook towards life and celebrate the culture of the city of Bengaluru. Join us to have a great time and start your journey towards a happy and healthy living and celebrate life to the fullest.\n\nFor any information about the event, Call: +91 9980029919See more See less',
    date: 'NOV 24',
    title: '7th Edition Thump! Celebration Bengaluru Marathon 2019',
    place: 'Sun 04:45 UTC+05:30' },
  { description: 'Do you have an idea, there are people who earns more than top level employees just sitting in home. You can do it now. Just think out of the box. Now your hobbies can earn you money from the comforts of home. There are numerous ways of making money online, but only some of them works and some of them makes you celebrities as well and make you to stand out of crowd. We make you experts on those higher level ways of making money online. \nYou need not to have any technical knowledge. Our one day workshop is designed for basic beginner in this field and we will show you the path of exploration. This workshop is hands on and practical with real time cases and examples. We start from very basics and make you a professional by end of the day.\n\nTimings: 09.30 AM to 04.30 PM\n\nWhat you can do by end of workshop\n1)\tYou will be internet entrepreneur\n2)\tYou will be able to earn from your hobbies\n3)\tYou will be learning the key ways of earning online\n4)\tYou will have your own blog and will be blogger\n5)\tYou will start earning from youtube\n6)\tYou will be able to sell products on your blog\n7)\tYou will be a skilled professional in freelancing with number of skills\n8)\tLearn tools of earning online\n\nWho should attend?\n•\tHousewives\n•\tSchool & College Level students\n•\tPeople looking out to earn from their hobbies\n•\tBeginners looking for guidance\n•\tWorking professional and well as job seekers\n•\tProfessionals looking for a second income\n•\tPeople who want explore this field without any technical knowledge\n•\tAnyone looking for a good field to explore (All ages)\n\nPre-requisites\nYou should know the basic usage of computers and internet.\n\nCore Modules:\nIntroduction:\n•\tDifferent ways of making money online\n•\tIntroduction to successful ways of earning\n•\tHow making money works\n•\tReal time examples of successful people\n\nBasics:\n•\tDo people really make money blogging\n•\tHow a blogger makes 1 Lakh per month\n•\tBlogging Tools and platforms\n•\tInteresting case studies & secrets\n•\tSetup your blog & related information\n•\tHow to setup a website\n•\tHow blog and blogging works\n•\tHow to do blogging and techniques\n•\tBasics of SEO & Killer SEO Techniques\n•\tDriving traffic to your blog\n•\tHow to increase Social Media Presence\n•\tSetup your Youtube Channel\n•\tHow to handle Youtube Channel\n•\tHow Youtube channel works and making money\n•\tHow to earn from Facebook without any investment\n•\tImportant tools for blogging and Youtube channel\n•\tIntroduction to most effective freelance platforms\n•\tHow to earn from Freelancing platforms\n\nAdvanced:\n•\tSetup Google adsense\n•\tIntroduction to Affiliate Marketing\n•\tSelling products on your blog\n•\tMaking money from Amazon and Ebooks\n•\tBasic Introduction to Digital Marketing\n•\tDifference between Affiliate & Adsense\n•\tSecrets behind zero investment ecommerce business\n\nAfter Workshop:\n•\tQ&A Session\n•\tGuidance on further steps\n\nKey Takeaways\n•\tOfficial Blogger Certification from Digitalshala with partnerships to add for your blog\n•\tEndorsements on your LinkedIn accounts from Digitalshala\n•\tVideo Tutorials for all the techniques discussed.\n•\tEbooks for all the topics discussed.\n•\tAccess to our LMS Website with all the materials for revision and further guidance\n•\tDedicated Guide for further guidance and any help in future\n•\tLife time Membership to Digitalshala Meetups\n\nAbout the Trainer\nThe trainer handling the workshop, is a blogger entrepreneur, digital marketer, web developer, graphic designer, investor and most importantly a good story teller, and is experienced in the digital world for more than 8 years. He is founder of two Advertising agencies and is an active investor in Education and Literacy field.\n\nPlease Note:\nWe will provide you a simple yet healthy lunch, snacks & refreshments\nSpecial arrangements can be made to aged people upon request based on availability\nSnacks and Lunch will be provided at the venue. We have ample parking facility at the venue.\nWorkshop is confined to Limited Seats only, first come first serve basis.See more See less',
    date: 'DEC 15',
    title: '2nd Income: Workshop on Art of Making Money Online',
    place: 'Sun 09:30 UTC+05:30 · Bangalore, India · Bangalore, India' },
  { description: 'The members of Sarathi Socio-Cultural Trust cordially invite you, your family & friends to attend Durgotsav2019.\nLet the Food, Service and Music whisk you back to Kolkata....See more See less',
    date: 'OCT 3',
    title: 'Durgotsav 2019 - 3rd - 8th October',
    place: '3 Oct–4 Oct · Sarathi Socio-Cultural Trust, Koramangala · Bangalore, India' },
  { description: 'Real Patan Patola & Bandhej Exhibition \nSarees | Dupattas | Shawls\n\n11-12-13 October 11AM To 7PM\n\nVenue: RAIN TREE Gallery,\nNo 4, Sankey Road, Opp ITC Windsor Hotel, Bangalore.\n\nMo 9033235235See more See less',
    date: 'OCT 11',
    title: 'Patola & Bandhej Exhibition At RainTree Bangalore, Mo 9033235235',
    place: '11 Oct–13 Oct · Raintree Store · Bangalore, India' },
  { description: 'Bangalore\'s biggest flea market is back and we\'re here to light up your Diwali. Come celebrate the festival of lights with us on the 13th of October at Jayamahal Palace. Bursting with colours, culture and flavour, this is one Soul Sante you don\'t want to miss!See more See less',
    date: 'OCT 13',
    title: 'Sunday Soul Sante Diwali Edition, October 13th 2019',
    place: 'Sun 10:00 UTC+05:30 · Jayamahal Palace · Bangalore, India' },
  { description: 'Barsha\'s most anticipated event is our flagship Durga Puja. Come and join with family and friends for the "Award Winning Best Durga Puja 2018" biggest extravaganza in HSR Layout. Be a member and join the family - be a part of the festival extravaganza where music, food & culture comes alive.See more See less',
    date: 'OCT 3',
    title: 'Barsha Durga Puja 2019',
    place: '3 Oct–8 Oct · Barsha · Bangalore, India' },
  { description: 'India\'s Biggest Pet Festival is back with its 2nd edition in Bangalore at a New, Much Bigger and Greener Location, at Jayamahal Palace! Join us at Just Dogs presents PET FED Bengaluru 2019 powered by PURINA India, co-powered by Flying Fur, with or without your pets for 2 days of unlimited fun, activities, shopping & more, such as:\n\n- 3 Acres of Festival Area\n- Dedicated Play Zones for Dogs & Cats\n- International Cat Show \n- Fashion Show with #DinoMorea\n- Police Dog Show \n- Exclusive Agility Ring\n- Adoption Camps\n- 100+ Stalls for Your Pets from Across the Globe\n- Food & Drinks\n...And Find out More at bengaluru.petfed.org \nBook Y... See more | See less',
    date: 'NOV 16',
    title: 'PET FED Bengaluru 2019',
    place: 'Sat 11:00 UTC+05:30 · Jayamahal Palace · Bangalore, India' },
  { description: 'Welcome to the 51st edition of Socio Cultural Association\'s Durga Puja & Dussera Celebration!  \n\nFor all six days, starting পঞ... See more See less',
    date: 'OCT 3',
    title: 'Socio Cultural Association\'s Durga Puja 2019',
    place: '3 Oct–8 Oct · Socio Cultural Association · Bangalore, India' },
  { description: '#DVLM will be performing live this November at Sunburn Arena in #Bangalore on 7th November.\n.\nPasses starting from 499/- only.... See more See less',
    date: 'NOV 7',
    title: 'Sunburn Arena with DVLM • BLR',
    place: 'Thu 17:00 UTC+05:30 · Bangalore, India · Bangalore, India' },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {} ]